[package]
name = "func-union"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
func-union-macro = { version = "0.1.0", path = "macro" }
